library(car)
AirPassengers
iris
mean(iris$Petal.Length)
a<-(iris$Petal.Length-mean(iris$Petal.Length))/sd(iris$Petal.Length)
a
summary(a)
sd(a)
b<-(iris$Petal.Length-min(iris$Petal.Length))/(max(iris$Petal.Length)-min(iris$Petal.Length))
b
summary(b)
hist(b)
hist(a)
c<-rnorm(1000)
c
hist(c)
sd(c)
d<-rlogis(1000)
hist(d)
mean(d)
qqPlot(c)
qqline(c)
qqPlot(d)
qqline(d)
qqnorm(c)
qqnorm(d)
